# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Runs application
    cmds:
      - go run ./cmd/abyss-blackbox/
    silent: true

  test:
    desc: Run all the go tests.
    cmds:
      - go test ./...

  install-deps:
    desc: Install dependencies needed to build release
    cmds:
      - go install github.com/gonutz/rsrc@latest
    silent: true

  resources:
    desc: Compile resource file
    cmds:
      - rsrc -manifest ./cmd/abyss-blackbox/main.manifest -ico ./trig_96x96.ico,./images/plus.ico,./images/switch-char.ico -o ./cmd/abyss-blackbox/rsrc.syso 

  debug:
    desc: Builds artifacts for release
    deps: [install-deps, resources]
    cmds:
      - go generate ./...
      - go build -trimpath -ldflags="-s -w" -o abyss-blackbox.exe ./cmd/abyss-blackbox 
      - go build -trimpath -ldflags="-s -w" ./cmd/extract/

  release:
    desc: Builds artifacts for release
    deps: [install-deps, resources]
    cmds:
      - go generate ./...
      - go build -trimpath -ldflags="-H windowsgui -s -w" -o abyss-blackbox.exe ./cmd/abyss-blackbox 
      - go build -trimpath -ldflags="-s -w" ./cmd/extract/
